# Charte graphique

## <p style="background-color:#1A5276; color:#FFFFFF; padding:15px; border-radius:6px; font-size:22px; font-weight:bold;">1. Section principale</p>

### <p style="background-color:#2980B9; color:#FFFFFF; padding:10px 15px; border-radius:5px; font-size:18px; font-weight:bold;">1.1 Sous-section</p>

#### <p style="background-color:#AED6F1; color:#1A5276; padding:8px 15px; border-radius:4px; font-size:15px; font-weight:bold;">1.1.1 Sous-sous-section</p>

##### <p style="background-color:#b8d1e2;color:black; padding:8px 15px; border-radius:4px; font-size:15px; font-weight:bold;">1.1.1.x.x.x. Toutes les autres sous-section</p>

# <p style="background: linear-gradient(90deg, #1A5276, #2980B9); color:#FFFFFF; padding:30px; border-radius:10px; text-align:center;"><span style="font-size:34px; font-weight:bold;">Identifiez les causes d'attrition au sein de l'ESN TechNova Partners</span><br></p>

## <p style="background-color:#1A5276; color:#FFFFFF; padding:15px; border-radius:6px; font-size:22px; font-weight:bold;">0. Import</p>

### <p style="background-color:#2980B9; color:#FFFFFF; padding:10px 15px; border-radius:5px; font-size:18px; font-weight:bold;">0.1 Import librairie</p>

In [ ]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
import plotly.subplots as sp
from scipy.stats import mannwhitneyu
import matplotlib.pyplot as plt

### <p style="background-color:#2980B9; color:#FFFFFF; padding:10px 15px; border-radius:5px; font-size:18px; font-weight:bold;">0.2 - Import des DataSet</p>

In [ ]:
eval = pd.read_csv("data/extrait_eval.csv")
sirh = pd.read_csv("data/extrait_sirh.csv")
sondage = pd.read_csv("data/extrait_sondage.csv")

## <p style="background-color:#1A5276; color:#FFFFFF; padding:15px; border-radius:6px; font-size:22px; font-weight:bold;">1. - DataSet extrait_eval.csv</p>

### <p style="background-color:#2980B9; color:#FFFFFF; padding:10px 15px; border-radius:5px; font-size:18px; font-weight:bold;">1.1 - Analyse préliminaire</p>

In [ ]:
eval.info()

Toutes les valeur sont remplies aucune vide

In [ ]:
eval.describe().T

In [ ]:
eval.head(2)

In [ ]:
for col in eval.columns:
    print(f" {col} : {eval[col].unique()}\n============================")

##### <p style="background-color:#b8d1e2;color:black; padding:8px 15px; border-radius:4px; font-size:15px; font-weight:bold;">1.2.1 - Tableaux des variables</p>

| Variable| Descritpion | A garder ? |valeur type |
|:-------|:------|:-------:|-------:  |
| satisfaction_employee_environnement|Note de satisfaction sur l'environement|oui|1 à 4|
| note_evaluation_precedente     |Peut être la note donné par le responssable|  non |1 à 4  |
| niveau_hierarchique_poste     |Peut être le niveau de hierachie du poste| oui  | 1 à 5 |
| satisfaction_employee_nature_travail     |Note donné pour jugé si ce qu'il fait lui plait| oui  |1 à 4|
| satisfaction_employee_equipe      |Note pour la relation equipe| oui|1 à 4  |
| satisfaction_employee_equilibre_pro_perso      |Note pour l'mpietement du pro sur le perso| oui |1 à 4|
| eval_number      |Numéro de l'évaliation | non |E_1 / E_2  |
| note_evaluation_actuelle     |idem note precedente  |non| 3 ou 4|
| heure_supplementaires     | S'il fait des heures sup  |oui       |oui / non |
| augementation_salaire_precedente     |Valeur de l'augementation|oui  |en %     |

In [ ]:
eval_clean = eval.drop(columns=["note_evaluation_precedente","eval_number","note_evaluation_actuelle"])

### <p style="background-color:#2980B9; color:#FFFFFF; padding:10px 15px; border-radius:5px; font-size:18px; font-weight:bold;">1.2 - Répartition des notes</p>

In [ ]:
# apply value_counts() sur chaque colonne séparément
df_counts = eval[['satisfaction_employee_environnement','satisfaction_employee_nature_travail',
       'satisfaction_employee_equipe',
       'satisfaction_employee_equilibre_pro_perso']].apply(pd.Series.value_counts)
df_counts

In [ ]:
fig = px.bar(df_counts, barmode="group")
fig.show()

## <p style="background-color:#1A5276; color:#FFFFFF; padding:15px; border-radius:6px; font-size:22px; font-weight:bold;">2. - DataSet extrait_sirh.csv</p>

### <p style="background-color:#2980B9; color:#FFFFFF; padding:10px 15px; border-radius:5px; font-size:18px; font-weight:bold;">2.1 - Analyse préliminaire</p>

In [ ]:
sirh.info()

In [ ]:
sirh.describe().T

In [ ]:
sirh.head(2)

In [ ]:
for col in sirh.columns:
    print(f" {col} : {sirh[col].unique()}\n============================")

##### <p style="background-color:#b8d1e2;color:black; padding:8px 15px; border-radius:4px; font-size:15px; font-weight:bold;">2.1.1 - Tableaux des variables</p>

| Variable| Descritpion | A garder ? |valeur type |
|:-------|:------|:-------:|-------:  |
|   id_employee    |       |     non  |    numéro   |
|  age   |       |     oui  |       |
|   genre  |       |     oui  |       |
|  revenu_mensuel   |probablement le coût total du salarié|     oui  |       |
|  statut_marital   |       |     oui  |  Célibataire, Marié(e), Divorcé(e)     |
|  departement   |       |     oui  | Commercial, Consulting, Ressources Humaines      |
|  poste   |       |     oui  |       |
|  nombre_experiences_precedentes   |       |     oui  |  nombres     |
|   annees_dans_l_entreprise  |       |     oui  |   années    |
|  annees_dans_le_poste_actuel   |       |     oui  |     années  |
|   nombre_heures_travailless  |       |     non |   toujours 80    |
|   annee_experience_totale  |       |     non  |    années   |

In [ ]:
sirh_clean =  sirh.drop(columns=["id_employee","nombre_heures_travailless","annee_experience_totale"])

## <p style="background-color:#1A5276; color:#FFFFFF; padding:15px; border-radius:6px; font-size:22px; font-weight:bold;">3. - DataSet extrait_sondage.csv</p>

### <p style="background-color:#2980B9; color:#FFFFFF; padding:10px 15px; border-radius:5px; font-size:18px; font-weight:bold;">3.1 - Analyse préliminaire</p>

In [ ]:
sondage.info()

In [ ]:
sondage.describe().T

In [ ]:
sondage.head(2)

In [ ]:
for col in sondage.columns:
    print(f" {col} : {sondage[col].unique()}\n============================")

##### <p style="background-color:#b8d1e2;color:black; padding:8px 15px; border-radius:4px; font-size:15px; font-weight:bold;">3.1.1 - Tableaux des variables</p>

| Variable| Descritpion | A garder ? |valeur type |
|:-------|:------|:-------:|-------:  |
| a_quitte_l_entreprise|          |oui    | oui/non        |
| nombre_participation_pee |Participation Plan d'Épargne Entreprise|oui    |  0,1,2,3    |
|  nb_formations_suivies      |          |oui    |   0,3,2,5,1,4,6     |
|  nombre_employee_sous_responsabilite      |          |non    |   toujours 1      |
|   code_sondage     |identifiant du sondage |non    |         |
|    distance_domicile_travail    |          |oui    |   km ?      |
|     niveau_education   |          |oui    |  2, 1, 4, 3, 5       |
|     domaine_etude   |          |oui    |         |
|     ayant_enfants   |          |non    |  Tous Y pour yes surement      |
|     frequence_deplacement   |          |oui    | Occasionnel, Frequent, Aucun        |
|     annees_depuis_la_derniere_promotion   |          |oui    |  années       |
|     annes_sous_responsable_actuel   |          |oui    |     années    |

In [ ]:
sondage_clean = sondage.drop(columns=["nombre_employee_sous_responsabilite", "code_sondage", "ayant_enfants"])

### <p style="background-color:#2980B9; color:#FFFFFF; padding:10px 15px; border-radius:5px; font-size:18px; font-weight:bold;">3.2 - Analyse a_quitte_l_entreprise</p>

#### <p style="background-color:#AED6F1; color:#1A5276; padding:8px 15px; border-radius:4px; font-size:15px; font-weight:bold;">3.2.1 Graph de répartion</p>

Il y a juste marqué s'il ont quitté l'entreprise, pas si il sont partie d'eux même, ni la nature de la rupture (démission, licensiement, Rupture conventionnelle )

In [ ]:
df = sondage["a_quitte_l_entreprise"].value_counts().reset_index()
fig = go.Figure(data=[go.Pie(labels=['Non','Oui'],
                             values=df["count"])])
fig.update_traces(hoverinfo='label+percent', textinfo='value+percent', textfont_size=20,
                  )
fig.show()

#### <p style="background-color:#AED6F1; color:#1A5276; padding:8px 15px; border-radius:4px; font-size:15px; font-weight:bold;">3.2.1 Analyse de ceux qui sont parties</p>

In [ ]:
df_demission = sondage[sondage.a_quitte_l_entreprise == "Oui"]
df_demission

## <p style="background-color:#1A5276; color:#FFFFFF; padding:15px; border-radius:6px; font-size:22px; font-weight:bold;">4. Jointure</p>

### <p style="background-color:#2980B9; color:#FFFFFF; padding:10px 15px; border-radius:5px; font-size:18px; font-weight:bold;">4.1 - Jointure</p>

In [ ]:
df_merge = pd.merge(sirh_clean, eval_clean, left_index=True, right_index=True)
df_merge = pd.merge(df_merge, sondage_clean, left_index=True, right_index=True)
df_merge

In [ ]:
df_merge.info()

### <p style="background-color:#2980B9; color:#FFFFFF; padding:10px 15px; border-radius:5px; font-size:18px; font-weight:bold;">4.2 - Analyse de la jointure</p>

In [ ]:
df_merge.head()

On vois de trés forte corrélation entre certaine variable, certaine sont attendu. 
- niveau_hierachique / revenu_mensuel (0.95 - Attendu)
- annees_dans_le_poste_actuel / annees_dans_l_entreprise (0.76 - Attendu)
- annees_depuis_la_derniere_promotion / annees_dans_l_entreprise (0.62 - moins evident commme corrélation)
- annes_sous_responsable_actuel / annees_dans_le_poste_actuel (0.71 - Attendu)
- annes_sous_responsable_actuel / annees_dans_l_entreprise (0.77 - Attendu)

**annees_dans_l_entreprise** : apparaît 3 fois, peut êtres n'est elle pas nécéssaire si elle peut être trouver par les autre, variable

#### <p style="background-color:#AED6F1; color:#1A5276; padding:8px 15px; border-radius:4px; font-size:15px; font-weight:bold;">4.1.1 Transformation numérique de certaine variable</p>

In [ ]:
df_merge.select_dtypes(include='object').nunique()

In [ ]:
#Transformation de genre en M=0 F=1
df_merge.genre = df_merge.genre.apply(lambda x: 0 if x=='M' else 1)
#Transformation de heure_supplementaires en Non=0 Oui=1
df_merge.heure_supplementaires = df_merge.heure_supplementaires.apply(lambda x: 0 if x=='Non' else 1)
#Transformation de a_quitte_l_entreprise Non=0 Oui=1
df_merge.a_quitte_l_entreprise = df_merge.a_quitte_l_entreprise.apply(lambda x: 0 if x=='Non' else 1)

#### <p style="background-color:#AED6F1; color:#1A5276; padding:8px 15px; border-radius:4px; font-size:15px; font-weight:bold;">4.1.2 Analyse de corrélation graphique</p>

In [ ]:
#Calculer la matrice de corrélation
corr_matrix = df_merge.corr(numeric_only=True)



# Créer un masque pour cacher le triangle supérieur (garder diagonale + inférieur)
mask = np.triu(np.ones_like(corr_matrix, dtype=bool), k=1)
corr_masked = corr_matrix.mask(mask)  # remplace par NaN les valeurs masquées

fig = px.imshow(
    corr_masked,
    text_auto=".2f",
    color_continuous_scale="RdBu_r",
    zmin=-1, zmax=1,
    aspect="auto"
)

fig.update_layout(
    width=1000,   # agrandir en largeur
    height=600,  # agrandir en hauteur (carré car matrice carrée)
    xaxis=dict(tickangle=45, dtick=1),  # dtick=1 force l'affichage de CHAQUE label
    yaxis=dict(dtick=1)
)
fig.show()

In [ ]:
higt_corr = np.where((corr_masked > 0.7) & (corr_masked < 1))
index, col = higt_corr
for i, col in zip(index, col):
    print(f"{corr_masked.index[i]} / {corr_masked.columns[col]} : {corr_masked.iloc[i,col]}")
index_drop = [corr_masked.index[i] for i in index]
features_drop = np.unique(index_drop)
print("Feature à supprimer : ",features_drop)

In [ ]:
# Comparaison des 17 variables numériques selon la variable cible

#data frame contenant uniquement les variable numérique et le target 
df = df_merge.select_dtypes(include="int64").copy()

target_column = "a_quitte_l_entreprise"  # remplace par ta colonne cible

df[target_column] = df_merge[target_column]



numeric_columns = df.columns 
numeric_columns = numeric_columns.drop(target_column)

# --- Séparation des variables selon leur nature ---
# Ordinales à faible cardinalité (échelles de notation, catégories discrètes peu nombreuses)
ordinal_columns = [
    "satisfaction_employee_environnement", "niveau_hierarchique_poste",
    "satisfaction_employee_nature_travail", "satisfaction_employee_equipe",
    "satisfaction_employee_equilibre_pro_perso", "nombre_participation_pee",
    "nb_formations_suivies", "niveau_education", "nombre_experiences_precedentes",
    "genre", "heure_supplementaires"
]

# Continues (à traiter en violin, potentiellement avec échelle log)
continuous_columns = [col for col in df.columns if col not in ordinal_columns + [target_column]]

# Colonnes continues fortement skewed à droite -> candidates au log1p
log_scale_columns = [
    "revenu_mensuel", "distance_domicile_travail",
    "annees_dans_l_entreprise", "annees_dans_le_poste_actuel",
    "annees_depuis_la_derniere_promotion", "annees_sous_responsable_actuel"
]

positive_label, negative_label = "Oui", "Non"  # adapte si encodage 1/0

n_cols = 3
n_rows = -(-len(numeric_columns) // n_cols)  # ceil division
corrected_alpha = 0.05 / len(numeric_columns)  # correction Bonferroni 
p_values = {}

In [ ]:
#Voir quel variable sont skew (asymétrique)
for col in continuous_columns:
    print(f"{col} : {df[col].skew()}")

- proche de 0 = symétrique, 
- positif = skew droite, 
- négatif = skew gauche 
Au-delà de |skew| > 1, on considère généralement que c'est suffisamment marqué pour justifier une transformation (log1p par exemple)

| Variable | Skew | Décision log1p |
|---|---|---|
| `age` | 0.41 | **Non** — quasi symétrique |
| `revenu_mensuel` | 1.37 | **Oui** — au-dessus du seuil |
| `annees_dans_l_entreprise` | 1.76 | **Oui** — fortement skewed |
| `annees_dans_le_poste_actuel` | 0.92 | **Limite** — juste en dessous du seuil |
| `distance_domicile_travail` | 0.96 | **Limite** — juste en dessous du seuil |
| `annees_depuis_la_derniere_promotion` | 1.98 | **Oui** — la plus skewed de toutes |
| `annes_sous_responsable_actuel` | 0.83 | **Limite/Non** — en dessous du seuil |

In [ ]:
#transformation des variable skewed en log1p

col = ["revenu_mensuel",
                 "annees_dans_l_entreprise",
                  "annees_dans_le_poste_actuel",
                  "distance_domicile_travail",
                  "annees_depuis_la_derniere_promotion",
                  "annes_sous_responsable_actuel" ]
df[col] = np.log(df[col]+1)
df.head()

In [ ]:
n_cols = 3
n_rows = -(-len(continuous_columns) // n_cols)

fig_violin = sp.make_subplots(rows=n_rows, cols=n_cols, subplot_titles=continuous_columns)

for idx, col in enumerate(continuous_columns):
    row = idx // n_cols + 1
    col_pos = idx % n_cols + 1

    group_pos = df.loc[df[target_column] == positive_label, col].dropna()
    group_neg = df.loc[df[target_column] == negative_label, col].dropna()

    stat, p_value = mannwhitneyu(group_pos, group_neg, alternative="two-sided")
    p_values[col] = p_value

    use_log = col in log_scale_columns

    # log1p appliqué manuellement plutôt que log_y=True de px,
    # car log1p gère les zéros (log(1+0)=0) contrairement à log_y qui plante sur les 0
    plot_df = df.copy()
    if use_log:
        plot_df[col] = np.log1p(plot_df[col])

    violin_fig = px.violin(plot_df, x=target_column, y=col)
    for trace in violin_fig.data:
        fig_violin.add_trace(trace, row=row, col=col_pos)

    marker = "*" if p_value < corrected_alpha else ""
    label_suffix = " [log1p]" if use_log else ""
    fig_violin.layout.annotations[idx].text = f"{col}{label_suffix}<br>(p={p_value:.3f}){marker}"

fig_violin.update_layout(
    height=300 * n_rows, width=350 * n_cols, showlegend=False,
    title_text="Comparaison des variables continues selon le départ de l'entreprise"
)
fig_violin.show()

In [ ]:

# =========================================================
# GRAPHIQUE 2 : HISTOGRAMMES POUR LES VARIABLES ORDINALES
# =========================================================
n_rows_hist = -(-len(ordinal_columns) // n_cols)

fig_hist = sp.make_subplots(rows=n_rows_hist, cols=n_cols, subplot_titles=ordinal_columns)

for idx, col in enumerate(ordinal_columns):
    row = idx // n_cols + 1
    col_pos = idx % n_cols + 1

    group_pos = df.loc[df[target_column] == positive_label, col].dropna()
    group_neg = df.loc[df[target_column] == negative_label, col].dropna()

    stat, p_value = mannwhitneyu(group_pos, group_neg, alternative="two-sided")
    p_values[col] = p_value

    hist_fig = px.histogram(
        df, x=col, color=target_column,
        barmode="group",
        histnorm="percent"  # proportions, pas comptes bruts (groupes de tailles différentes)
    )
    for trace in hist_fig.data:
        fig_hist.add_trace(trace, row=row, col=col_pos)

    marker = "*" if p_value < corrected_alpha else ""
    fig_hist.layout.annotations[idx].text = f"{col}<br>(p={p_value:.3f}){marker}"

fig_hist.update_layout(
    height=300 * n_rows_hist, width=350 * n_cols, showlegend=True,
    title_text="Comparaison des variables ordinales selon le départ de l'entreprise"
)
fig_hist.show()

## <p style="background-color:#1A5276; color:#FFFFFF; padding:15px; border-radius:6px; font-size:22px; font-weight:bold;">5. Choix du modéle</p>

In [70]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.model_selection import StratifiedKFold, train_test_split,cross_val_score, cross_validate, cross_val_predict
from sklearn.metrics import confusion_matrix
import shap
from sklearn.linear_model import LogisticRegression
from lightgbm import LGBMClassifier

### <p style="background-color:#2980B9; color:#FFFFFF; padding:10px 15px; border-radius:5px; font-size:18px; font-weight:bold;">5.1 - Teste des modeles</p>

In [81]:
#Parametrage de base identique à tous les modéles

#Valeur random_state identique à tous les modéles
random_state = 42


#Tableau contenant les scores des modeles
df_model_score = pd.DataFrame()
#dictionnaire contenant tous les modéle par génération
dict_model = {}

#incrementation des génération pour comparaison
generation = 0

#Définition du schéma de validation croisée
cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=random_state
)

In [82]:
#Split initial train/test
X = df_merge.drop(columns=target_column).copy()
y= df_merge[target_column].copy()

X_train_val, X_test, y_train_val, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    stratify=y,
    random_state=random_state
)

# Identifier les colonnes categoriel
numeric_cols = X_train_val.select_dtypes(include=['int64', 'float64']).columns
categorical_cols = X_train_val.select_dtypes(include=['object']).columns

preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(drop='first', handle_unknown='ignore'), categorical_cols)
    ],
    remainder='passthrough'
)

C:\Users\Jerem\AppData\Local\Temp\ipykernel_9908\796495963.py:15: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = X_train_val.select_dtypes(include=['object']).columns

On compare deux model RandomForest et XGBoost que l'ont va entrainer avec des données croisé et comparer à l'aide de la métrique AUC-PR qui se prette bien au données asymétrique avec moins de vrai positif que de faux négatif

On commence par des modéles paramétrè par défault pour avoir une base

Métriques de classification

- Accuracy - proportion de prédictions correctes (VP+VN)/total
cross_val_score(model, X, y, scoring='accuracy')

- Precision - VP/(VP+FP) : fiabilité des prédictions positives
cross_val_score(model, X, y, scoring='precision')

- Recall - VP/(VP+FN) : capacité à détecter les positifs
cross_val_score(model, X, y, scoring='recall')

- F1-score - moyenne harmonique precision/recall
cross_val_score(model, X, y, scoring='f1')

- ROC AUC - aire sous la courbe ROC, mesure la séparabilité des classes
cross_val_score(model, X, y, scoring='roc_auc')

- Average precision - aire sous la courbe precision-recall
cross_val_score(model, X, y, scoring='average_precision')

- Balanced accuracy - moyenne du recall par classe (utile si classes déséquilibrées)
cross_val_score(model, X, y, scoring='balanced_accuracy')

- Log loss (négatif, car sklearn maximise par convention)
cross_val_score(model, X, y, scoring='neg_log_loss')

In [83]:
#liste complétes de tous les noms valides de scoring installés dans la version de scikit-learn 
from sklearn.metrics import get_scorer_names
print(get_scorer_names())

['accuracy', 'adjusted_mutual_info_score', 'adjusted_rand_score', 'average_precision', 'balanced_accuracy', 'completeness_score', 'd2_absolute_error_score', 'd2_brier_score', 'd2_log_loss_score', 'explained_variance', 'f1', 'f1_macro', 'f1_micro', 'f1_samples', 'f1_weighted', 'fowlkes_mallows_score', 'homogeneity_score', 'jaccard', 'jaccard_macro', 'jaccard_micro', 'jaccard_samples', 'jaccard_weighted', 'matthews_corrcoef', 'mutual_info_score', 'neg_brier_score', 'neg_log_loss', 'neg_max_error', 'neg_mean_absolute_error', 'neg_mean_absolute_percentage_error', 'neg_mean_gamma_deviance', 'neg_mean_poisson_deviance', 'neg_mean_squared_error', 'neg_mean_squared_log_error', 'neg_median_absolute_error', 'neg_negative_likelihood_ratio', 'neg_root_mean_squared_error', 'neg_root_mean_squared_log_error', 'normalized_mutual_info_score', 'positive_likelihood_ratio', 'precision', 'precision_macro', 'precision_micro', 'precision_samples', 'precision_weighted', 'r2', 'rand_score', 'recall', 'recall_macro', 'recall_micro', 'recall_samples', 'recall_weighted', 'roc_auc', 'roc_auc_ovo', 'roc_auc_ovo_weighted', 'roc_auc_ovr', 'roc_auc_ovr_weighted', 'top_k_accuracy', 'v_measure_score']

In [84]:
def train_model(models, generation):
    df = pd.DataFrame()   

    scoring=[ 'precision', 'recall', 'f1', 'roc_auc', 'balanced_accuracy']
    out_scores = ['test_precision', 'test_recall', 'test_f1', 'test_roc_auc', 'test_balanced_accuracy']

    show_score = pd.DataFrame({"metric":scoring+["custom"]})

    for name, model in models.items():
        
        #Envelope chaque modele dans un pipeline pour gérer l'ordre des process
        pipeline = Pipeline([
        ('preprocessor', preprocessor),
        ('classifier', model)
])

        scores = cross_validate(
            pipeline,          # on passe la pipeline, pas le modèle seul
            X_train_val,
            y_train_val,
            cv=cv,
            scoring=scoring,
        )

        #cacul d'une metrique custom pour voir
        #on utilise cross_val_predict pour recuperer la matrice de confusion 
        y_pred = cross_val_predict(pipeline, X_train_val, y_train_val, cv=StratifiedKFold(n_splits=5))

        #recuperation des valeur de la matrice de confusion
        tn, fp, fn, tp = confusion_matrix(y_train_val, y_pred).ravel()
        #Calcul custom ((TP_predi/TP_total) + (TN_predi/TP_total) )/ 2         
        custom_metrix =   (tp/np.sum(y_train_val==1) + tn/np.sum(y_train_val==0)) / 2
        

        #On crée une ligne avec les information qui sera afficher à la fin avec les autres model
        show_score[name] = [f"{scores[out_key].mean():.4f} - (+/-){scores[out_key].std():.4f}" for out_key in out_scores] + [custom_metrix]

        metrics_dict = {}
        for name_score, out_key in zip(scoring, out_scores):
            metrics_dict[f"{name_score}"] = [round(scores[out_key].mean(),4)]
            metrics_dict[f"{name_score}_std"] = [round(scores[out_key].std(),4)]  
        metrics_dict["custom"] = [custom_metrix]      

        new_score = pd.DataFrame({"model": [name], "generation": [generation], **metrics_dict})
        df = pd.concat([df, new_score], ignore_index=True)

        


    display(show_score)

    return df

In [85]:
#Modele par default
generation += 1

models = {
    "Random Forest": RandomForestClassifier(random_state=random_state),
    "XGBoost": XGBClassifier(random_state=random_state),
    "Logistic Regression": LogisticRegression(random_state=random_state),
    "LightGBM": LGBMClassifier(random_state=random_state, verbosity=-1 )
}

dict_model[generation] = models
new_score = train_model(models=models, generation=generation)

df_model_score = pd.concat([df_model_score, new_score], ignore_index=True)

d:\Documents\CENTRE DE FORMATON\FORMATION IA\Projet 10\Mission_ESN\esn\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
d:\Documents\CENTRE DE FORMATON\FORMATION IA\Projet 10\Mission_ESN\esn\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
d:\Documents\CENTRE DE FORMATON\FORMATION IA\Projet 10\Mission_ESN\esn\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
d:\Documents\CENTRE DE FORMATON\FORMATION IA\Projet 10\Mission_ESN\esn\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
d:\Documents\CENTRE DE FORMATON\FORMATION IA\Projet 10\Mission_ESN\esn\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
d:\Documents\CENTRE DE FORMATON\FORMATION IA\Projet 10\Mission_ESN\esn\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
d:\Documents\CENTRE DE FORMATON\FORMATION IA\Projet 10\Mission_ESN\esn\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
d:\Documents\CENTRE DE FORMATON\FORMATION IA\Projet 10\Mission_ESN\esn\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
d:\Documents\CENTRE DE FORMATON\FORMATION IA\Projet 10\Mission_ESN\esn\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
d:\Documents\CENTRE DE FORMATON\FORMATION IA\Projet 10\Mission_ESN\esn\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
d:\Documents\CENTRE DE FORMATON\FORMATION IA\Projet 10\Mission_ESN\esn\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

,metric,Random Forest,XGBoost,Logistic Regression,LightGBM
0,precision,0.8878 - (+/-)0.1108,0.7020 - (+/-)0.0637,0.3333 - (+/-)0.3162,0.7287 - (+/-)0.0975
1,recall,0.2211 - (+/-)0.0678,0.3526 - (+/-)0.0657,0.0368 - (+/-)0.0488,0.3842 - (+/-)0.1034
2,f1,0.3456 - (+/-)0.0818,0.4656 - (+/-)0.0569,0.0652 - (+/-)0.0840,0.4931 - (+/-)0.0856
3,roc_auc,0.8016 - (+/-)0.0329,0.8245 - (+/-)0.0303,0.7689 - (+/-)0.0400,0.8197 - (+/-)0.0361
4,balanced_accuracy,0.6070 - (+/-)0.0311,0.6616 - (+/-)0.0304,0.5159 - (+/-)0.0242,0.6774 - (+/-)0.0470
5,custom,0.58957,0.681552,0.541283,0.662624

Les Modéle par défault on des bon resultat, avec un mieux pour XGBoost.
On va commencer par gérer le déséquilibre de classe pour voir s'il y à une amélioration

In [86]:
#Amélioration du déséquilibre de classe par pondération des classes 
generation += 1

# calcul manuel du ratio pour XGBoost
scale_pos_weight = (y_train_val == 0).sum() / (y_train_val == 1).sum()

models = {
    "Random Forest": RandomForestClassifier(random_state=random_state, class_weight="balanced"),
    "XGBoost": XGBClassifier(random_state=random_state, scale_pos_weight=scale_pos_weight),
    "Logistic Regression": LogisticRegression(random_state=random_state, class_weight="balanced"),
    "LightGBM": LGBMClassifier(random_state=random_state, class_weight="balanced",verbosity=-1 )
}
dict_model[generation] = models

new_score = train_model(models=models, generation=generation)

df_model_score = pd.concat([df_model_score, new_score], ignore_index=True)

d:\Documents\CENTRE DE FORMATON\FORMATION IA\Projet 10\Mission_ESN\esn\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
d:\Documents\CENTRE DE FORMATON\FORMATION IA\Projet 10\Mission_ESN\esn\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
d:\Documents\CENTRE DE FORMATON\FORMATION IA\Projet 10\Mission_ESN\esn\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
d:\Documents\CENTRE DE FORMATON\FORMATION IA\Projet 10\Mission_ESN\esn\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
d:\Documents\CENTRE DE FORMATON\FORMATION IA\Projet 10\Mission_ESN\esn\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
d:\Documents\CENTRE DE FORMATON\FORMATION IA\Projet 10\Mission_ESN\esn\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
d:\Documents\CENTRE DE FORMATON\FORMATION IA\Projet 10\Mission_ESN\esn\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
d:\Documents\CENTRE DE FORMATON\FORMATION IA\Projet 10\Mission_ESN\esn\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
d:\Documents\CENTRE DE FORMATON\FORMATION IA\Projet 10\Mission_ESN\esn\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
d:\Documents\CENTRE DE FORMATON\FORMATION IA\Projet 10\Mission_ESN\esn\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

,metric,Random Forest,XGBoost,Logistic Regression,LightGBM
0,precision,0.6142 - (+/-)0.0971,0.6274 - (+/-)0.0959,0.3109 - (+/-)0.0474,0.6064 - (+/-)0.1024
1,recall,0.3632 - (+/-)0.0990,0.4316 - (+/-)0.0567,0.6895 - (+/-)0.0788,0.4632 - (+/-)0.0842
2,f1,0.4511 - (+/-)0.0969,0.5078 - (+/-)0.0566,0.4281 - (+/-)0.0594,0.5233 - (+/-)0.0872
3,roc_auc,0.8044 - (+/-)0.0271,0.8163 - (+/-)0.0375,0.7473 - (+/-)0.0291,0.8247 - (+/-)0.0341
4,balanced_accuracy,0.6598 - (+/-)0.0480,0.6899 - (+/-)0.0290,0.6956 - (+/-)0.0552,0.7022 - (+/-)0.0475
5,custom,0.662912,0.703085,0.681985,0.699536

In [87]:
#Modification des features en retirant les feature qui sembles être fortement corrélé
generation += 1

df_lite = df_merge.drop(columns=features_drop)

#Split initial train/test
X = df_lite.drop(columns=target_column).copy()
y= df_lite[target_column].copy()

X_train_val, X_test, y_train_val, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    stratify=y,
    random_state=random_state
)

# Identifier les colonnes categoriel
numeric_cols = X_train_val.select_dtypes(include=['int64', 'float64']).columns
categorical_cols = X_train_val.select_dtypes(include=['object']).columns

preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(drop='first', handle_unknown='ignore'), categorical_cols)
    ],
    remainder='passthrough'
)


# calcul manuel du ratio pour XGBoost
scale_pos_weight = (y_train_val == 0).sum() / (y_train_val == 1).sum()

models = {
    "Random Forest": RandomForestClassifier(random_state=random_state, class_weight="balanced"),
    "XGBoost": XGBClassifier(random_state=random_state, scale_pos_weight=scale_pos_weight),
    "Logistic Regression": LogisticRegression(random_state=random_state, class_weight="balanced"),
    "LightGBM": LGBMClassifier(random_state=random_state, class_weight="balanced", verbosity=-1 )
}

dict_model[generation] = models

new_score = train_model(models=models, generation=generation)

df_model_score = pd.concat([df_model_score, new_score], ignore_index=True)

C:\Users\Jerem\AppData\Local\Temp\ipykernel_9908\3873159502.py:20: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = X_train_val.select_dtypes(include=['object']).columns
d:\Documents\CENTRE DE FORMATON\FORMATION IA\Projet 10\Mission_ESN\esn\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
d:\Documents\CENTRE DE FORMATON\FORMATION IA\Projet 10\Mission_ESN\esn\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
d:\Documents\CENTRE DE FORMATON\FORMATION IA\Projet 10\Mission_ESN\esn\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
d:\Documents\CENTRE DE FORMATON\FORMATION IA\Projet 10\Mission_ESN\esn\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
d:\Documents\CENTRE DE FORMATON\FORMATION IA\Projet 10\Mission_ESN\esn\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
d:\Documents\CENTRE DE FORMATON\FORMATION IA\Projet 10\Mission_ESN\esn\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
d:\Documents\CENTRE DE FORMATON\FORMATION IA\Projet 10\Mission_ESN\esn\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
d:\Documents\CENTRE DE FORMATON\FORMATION IA\Projet 10\Mission_ESN\esn\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
d:\Documents\CENTRE DE FORMATON\FORMATION IA\Projet 10\Mission_ESN\esn\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
d:\Documents\CENTRE DE FORMATON\FORMATION IA\Projet 10\Mission_ESN\esn\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

,metric,Random Forest,XGBoost,Logistic Regression,LightGBM
0,precision,0.6849 - (+/-)0.1266,0.6484 - (+/-)0.0706,0.3064 - (+/-)0.0264,0.6073 - (+/-)0.0939
1,recall,0.3895 - (+/-)0.1096,0.4526 - (+/-)0.0586,0.7105 - (+/-)0.0645,0.4842 - (+/-)0.0921
2,f1,0.4917 - (+/-)0.1175,0.5297 - (+/-)0.0503,0.4272 - (+/-)0.0309,0.5348 - (+/-)0.0862
3,roc_auc,0.8109 - (+/-)0.0319,0.8085 - (+/-)0.0179,0.7506 - (+/-)0.0304,0.8292 - (+/-)0.0231
4,balanced_accuracy,0.6780 - (+/-)0.0555,0.7020 - (+/-)0.0273,0.6991 - (+/-)0.0304,0.7112 - (+/-)0.0476
5,custom,0.670615,0.695698,0.694635,0.699029

In [91]:
#On ne garde que les feature qui on un SHAP au dessus de 0.15 par rapport au modéle 3
generation += 1

#Split initial train/test
X = df_merge[['departement', 'poste', 'augementation_salaire_precedente', 
                  'frequence_deplacement', 'age', 'revenu_mensuel', 
                  'nombre_experiences_precedentes', 'annees_dans_l_entreprise', 
                  'satisfaction_employee_environnement', 'satisfaction_employee_nature_travail', 
                  'satisfaction_employee_equipe', 'satisfaction_employee_equilibre_pro_perso', 
                  'heure_supplementaires', 'nombre_participation_pee', 'nb_formations_suivies', 
                  'distance_domicile_travail', 'annees_depuis_la_derniere_promotion', ]].copy()

y= df_merge[target_column].copy()

X_train_val, X_test, y_train_val, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    stratify=y,
    random_state=random_state
)

# Identifier les colonnes categoriel
numeric_cols = X_train_val.select_dtypes(include=['int64', 'float64']).columns
categorical_cols = X_train_val.select_dtypes(include=['object']).columns

preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(drop='first', handle_unknown='ignore'), categorical_cols)
    ],
    remainder='passthrough'
)

# calcul manuel du ratio pour XGBoost
scale_pos_weight = (y_train_val == 0).sum() / (y_train_val == 1).sum()

models = {
    "Random Forest": RandomForestClassifier(random_state=random_state, class_weight="balanced"),
    "XGBoost": XGBClassifier(random_state=random_state, scale_pos_weight=scale_pos_weight),
    "Logistic Regression": LogisticRegression(random_state=random_state, class_weight="balanced"),
    "LightGBM": LGBMClassifier(random_state=random_state, class_weight="balanced", verbose=-1 )
}

dict_model[generation] = models

new_score = train_model(models=models, generation=generation)

df_model_score = pd.concat([df_model_score, new_score], ignore_index=True)

C:\Users\Jerem\AppData\Local\Temp\ipykernel_9908\1721762994.py:25: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = X_train_val.select_dtypes(include=['object']).columns
d:\Documents\CENTRE DE FORMATON\FORMATION IA\Projet 10\Mission_ESN\esn\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
d:\Documents\CENTRE DE FORMATON\FORMATION IA\Projet 10\Mission_ESN\esn\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
d:\Documents\CENTRE DE FORMATON\FORMATION IA\Projet 10\Mission_ESN\esn\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
d:\Documents\CENTRE DE FORMATON\FORMATION IA\Projet 10\Mission_ESN\esn\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
d:\Documents\CENTRE DE FORMATON\FORMATION IA\Projet 10\Mission_ESN\esn\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
d:\Documents\CENTRE DE FORMATON\FORMATION IA\Projet 10\Mission_ESN\esn\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
d:\Documents\CENTRE DE FORMATON\FORMATION IA\Projet 10\Mission_ESN\esn\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
d:\Documents\CENTRE DE FORMATON\FORMATION IA\Projet 10\Mission_ESN\esn\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
d:\Documents\CENTRE DE FORMATON\FORMATION IA\Projet 10\Mission_ESN\esn\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
d:\Documents\CENTRE DE FORMATON\FORMATION IA\Projet 10\Mission_ESN\esn\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

,metric,Random Forest,XGBoost,Logistic Regression,LightGBM
0,precision,0.6612 - (+/-)0.0595,0.6162 - (+/-)0.0967,0.3001 - (+/-)0.0363,0.5925 - (+/-)0.0760
1,recall,0.4211 - (+/-)0.0781,0.4579 - (+/-)0.0428,0.6789 - (+/-)0.0805,0.4579 - (+/-)0.0698
2,f1,0.5109 - (+/-)0.0684,0.5207 - (+/-)0.0413,0.4142 - (+/-)0.0403,0.5107 - (+/-)0.0519
3,roc_auc,0.8066 - (+/-)0.0272,0.8113 - (+/-)0.0286,0.7475 - (+/-)0.0448,0.8243 - (+/-)0.0301
4,balanced_accuracy,0.6897 - (+/-)0.0372,0.6995 - (+/-)0.0195,0.6843 - (+/-)0.0382,0.6970 - (+/-)0.0304
5,custom,0.66675,0.68657,0.689757,0.70632

In [89]:
#Affichage du tableau comparatif des scores par model et par génération
df_model_score

,model,generation,precision,precision_std,recall,recall_std,f1,f1_std,roc_auc,roc_auc_std,balanced_accuracy,balanced_accuracy_std,custom
0,Random Forest,1,0.8878,0.1108,0.2211,0.0678,0.3456,0.0818,0.8016,0.0329,0.6070,0.0311,0.589570
1,XGBoost,1,0.7020,0.0637,0.3526,0.0657,0.4656,0.0569,0.8245,0.0303,0.6616,0.0304,0.681552
2,Logistic Regression,1,0.3333,0.3162,0.0368,0.0488,0.0652,0.0840,0.7689,0.0400,0.5159,0.0242,0.541283
3,LightGBM,1,0.7287,0.0975,0.3842,0.1034,0.4931,0.0856,0.8197,0.0361,0.6774,0.0470,0.662624
4,Random Forest,2,0.6142,0.0971,0.3632,0.0990,0.4511,0.0969,0.8044,0.0271,0.6598,0.0480,0.662912
5,XGBoost,2,0.6274,0.0959,0.4316,0.0567,0.5078,0.0566,0.8163,0.0375,0.6899,0.0290,0.703085
6,Logistic Regression,2,0.3109,0.0474,0.6895,0.0788,0.4281,0.0594,0.7473,0.0291,0.6956,0.0552,0.681985
7,LightGBM,2,0.6064,0.1024,0.4632,0.0842,0.5233,0.0872,0.8247,0.0341,0.7022,0.0475,0.699536
8,Random Forest,3,0.6849,0.1266,0.3895,0.1096,0.4917,0.1175,0.8109,0.0319,0.6780,0.0555,0.670615
9,XGBoost,3,0.6484,0.0706,0.4526,0.0586,0.5297,0.0503,0.8085,0.0179,0.7020,0.0273,0.695698
10,Logistic Regression,3,0.3064,0.0264,0.7105,0.0645,0.4272,0.0309,0.7506,0.0304,0.6991,0.0304,0.694635
11,LightGBM,3,0.6073,0.0939,0.4842,0.0921,0.5348,0.0862,0.8292,0.0231,0.7112,0.0476,0.699029
12,Random Forest,4,0.6612,0.0595,0.4211,0.0781,0.5109,0.0684,0.8066,0.0272,0.6897,0.0372,0.666750
13,XGBoost,4,0.6162,0.0967,0.4579,0.0428,0.5207,0.0413,0.8113,0.0286,0.6995,0.0195,0.686570
14,Logistic Regression,4,0.3001,0.0363,0.6789,0.0805,0.4142,0.0403,0.7475,0.0448,0.6843,0.0382,0.689757
15,LightGBM,4,0.5925,0.0760,0.4579,0.0698,0.5107,0.0519,0.8243,0.0301,0.6970,0.0304,0.706320

In [90]:
# List of metrics to plot (one subplot each)
metrics = ["precision", "recall", "f1", "roc_auc", "balanced_accuracy", "custom"]

# Create a 3x2 grid of subplots
fig = sp.make_subplots(
    rows=3, cols=2,
    subplot_titles=metrics,
    shared_xaxes=True
)

# Get consistent colors per model using plotly's qualitative palette
models = df_model_score["model"].unique()
colors = px.colors.qualitative.Plotly
color_map = {model: colors[i % len(colors)] for i, model in enumerate(models)}

# Loop over each metric, placing it in the right subplot position
for idx, metric in enumerate(metrics):
    row = idx // 2 + 1  # subplot row (1-indexed)
    col = idx % 2 + 1    # subplot col (1-indexed)

    for model_name in models:
        group_df_model_score = df_model_score[df_model_score["model"] == model_name].sort_values("generation")

        fig.add_trace(
            go.Scatter(
                x=group_df_model_score["generation"],
                y=group_df_model_score[metric],
                mode="lines+markers",
                name=model_name,
                legendgroup=model_name,
                # Show legend only once per model (on first subplot) to avoid duplicates
                showlegend=(idx == 0),
                line=dict(color=color_map[model_name])
            ),
            row=row, col=col
        )

fig.update_xaxes(title_text="Generation")
fig.update_layout(
    height=900, width=1000,
    title_text="Évolution des métriques par génération et par modèle"
)
fig.update_xaxes(showticklabels=True)

fig.show()

### <p style="background-color:#2980B9; color:#FFFFFF; padding:10px 15px; border-radius:5px; font-size:18px; font-weight:bold;">5.2 - Visualisation SHAP</p>

In [ ]:
# 1. Entraîner le pipeline final sur tout le train_val

VISUALISATINONMODEL_TO_VIEW = 4

final_pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('classifier', dict_model[VISUALISATINONMODEL_TO_VIEW]["XGBoost"])
])
final_pipeline.fit(X_train_val, y_train_val)

# 2. Extraire le préprocesseur et le modèle séparément du pipeline entraîné
fitted_preprocessor = final_pipeline.named_steps['preprocessor']
fitted_model = final_pipeline.named_steps['classifier']

# 3. Transformer les données AVANT de les passer à SHAP
# C'est l'étape cruciale : SHAP doit voir les données comme le modèle les voit
X_test_transformed = fitted_preprocessor.transform(X_test)

# 4. Récupérer les noms de features après transformation
# OneHotEncoder change les noms de colonnes (ex: "departement" devient "departement_RH", "departement_IT"...)
feature_names = fitted_preprocessor.get_feature_names_out()

# Convertir en DataFrame pour garder les noms de colonnes (SHAP les affiche mieux ainsi)

X_test_transformed_df = pd.DataFrame(X_test_transformed, columns=feature_names)

# 5. TreeExplainer est optimisé pour les modèles d'arbres (Random Forest, XGBoost, LightGBM)
# Il est exact et rapide, contrairement à KernelExplainer qui est plus lent et approximatif
explainer = shap.TreeExplainer(fitted_model)


# 6. Calculer les valeurs SHAP sur le jeu de test (ou un échantillon si trop volumineux)
shap_values = explainer.shap_values(X_test_transformed_df)

In [ ]:
shap.summary_plot(shap_values, X_test_transformed_df, show=False)
plt.tight_layout()
plt.show()

In [ ]:
shap.summary_plot(shap_values, X_test_transformed_df, plot_type="bar", show=False)
plt.tight_layout()
plt.show()

In [ ]:
#prendre les features au dessus d'un certain seuil

# Mean absolute SHAP value per column (= global importance per feature)
mean_abs_shap = np.abs(shap_values).mean(axis=0)

# Link values to column names
feature_importance = pd.Series(mean_abs_shap, index=X_test_transformed_df.columns)

# Filter by your threshold
threshold = 0.15
important_features = feature_importance[feature_importance >= threshold].index.tolist()

print(important_features)

In [ ]:
#recuperer les véritable nom des feature
cleaned_names = []
for name in important_features:
    if name.startswith("cat"):
        # remove everything before the first underscore AND after the last underscore
        first_split = name.split("__", 1)[1]      # drop "cat"
        variable_name = first_split.rsplit("_", 1)[0]  # drop modality after last "_"
    else:
        # remove only the prefix before the first underscore (i.e. "remainder")
        variable_name = name.split("__", 1)[1]

    cleaned_names.append(variable_name)

# dédoublonnage en conservant l'ordre d'apparition
unique_names = list(dict.fromkeys(cleaned_names))

display(unique_names)
print("Nombre de feature dont catégoriel : ",len(important_features))
print("Nombre de feature de base : ",len(unique_names))

In [ ]:
# List of features you want to compare (identified as important in summary_plot)

n_features = len(important_features)

# Create a grid of subplots: adjust nrows/ncols depending on how many features you have
n_cols = 3
n_rows = -(-n_features // n_cols)  # ceil division

fig, axes = plt.subplots(n_rows, n_cols, figsize=(14, 5 * n_rows))
axes = axes.flatten()  # easier to iterate even if grid is 2D

for i, feature in enumerate(important_features):
    shap.dependence_plot(
        feature,
        shap_values,
        X_test_transformed_df,
        ax=axes[i],       # key point: draw on this specific subplot
        show=False        # prevent SHAP from calling plt.show() itself
    )
   

# Hide any unused subplots if n_features is not a multiple of n_cols
for j in range(i + 1, len(axes)):
    fig.delaxes(axes[j])

plt.tight_layout()
plt.show()